### PR TITLE
fixed hcdev gossip bug, resolves #343

### LINKED ISSUE #343: Gossip not working

### PR DESCRIPTION
**Pull request by zippy**
problem was due to when NewNode was getting called in the gen sequence, it needs to be called after the DNA has is calculated and committed to the chain.  GenChain was calling NewNode (via Prepare) too early.

This fix also discovered that an error condition was not being returned, that might break some apps that didn't define a necessary genesis() function.

### CODE REVIEW

File: holochain.go [hunk 1]
```diff
@@ -372,10 +372,6 @@ func (h *Holochain) GenChain() (headerHash Hash, err error) {
 		}
 	}()
 
-	if err = h.Prepare(); err != nil {
-		return
-	}
-
```
Comment (lucksus) [inline holochain.go]: Why did having Prepare() here work when run in hcd?

**Comment by lucksus** [comment]
This doesn't fix the bug. Just tried running cointoss with @rayzer42 on two machines. Same problem. Also yesterday we've tried to take out the protoMux stuff completely and we still saw the same problem..

Basically these changes should be merged, but it does not resolve #343.
